import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { commandsBlock } from './context.js';
import { buildMandatoryStandards } from './standards.js';

// Generates a root AGENTS.md — the cross-tool standard read natively by Claude
// Code, Codex, Cursor, Copilot, Gemini CLI, Aider, Windsurf, Zed and others.
// Two zones:
//   - inside the markers: AUTO-generated from the code (refreshed every sync)
//   - below the markers: "## Project rules" — developer-maintained, PERSISTED
//     across syncs and meant to accumulate project/preference rules over time.
const MARKER_START = '<!-- promptpilot-ai:agents:start -->';
const MARKER_END = '<!-- promptpilot-ai:agents:end -->';
const RULES_HEADER = '## Project rules (developer-maintained)';

export function generateAgentsMd(cwd, scanData, target = 'both') {
  return applyAgentsMd(join(cwd, 'AGENTS.md'), buildBlock(scanData, target));
}

// Workspace-root AGENTS.md for a multi-repo workspace — an index of sub-repos.
export function generateRootAgentsMd(cwd, subRepos = []) {
  const list =
    subRepos
      .map((r) => `- \`${r.name}/\` — ${r.role || 'repo'}${r.framework ? ` (${r.framework})` : ''} — see \`${r.name}/AGENTS.md\``)
      .join('\n') || '- (no sub-repos detected)';

  const block = `${MARKER_START}
# AGENTS.md — workspace

> Auto-generated by promptpilot-ai. Multi-repo workspace: each sub-repo has its own \`AGENTS.md\` with its stack and mandatory standards. Read the relevant sub-repo's file before working in it.

## Sub-repos
${list}

## Cross-repo
- Frontend ↔ backend API map: \`.claude/context/bridge.md\` (if present).
- Apply each sub-repo's standards within that sub-repo.
${MARKER_END}`;

  return applyAgentsMd(join(cwd, 'AGENTS.md'), block);
}

// Write/refresh the auto block while PRESERVING everything outside the markers,
// and seed the developer-maintained "Project rules" section exactly once.
function applyAgentsMd(path, block) {
  const re = new RegExp(`${esc(MARKER_START)}[\\s\\S]*?${esc(MARKER_END)}`);
  let out;
  let status;

  if (!existsSync(path)) {
    out = block + '\n\n' + rulesSeed();
    status = 'created';
  } else {
    const existing = readFileSync(path, 'utf8');
    if (re.test(existing)) {
      // function replacement → `$` in `block` is inserted verbatim (no $&/$1 magic)
      out = existing.replace(re, () => block);
      status = 'updated';
    } else {
      // pre-existing AGENTS.md from another tool — put our block on top, keep theirs
      out = block + '\n\n' + existing.trimStart();
      status = 'merged';
    }
    // Seed Project rules only if the REAL section heading (own line) is absent —
    // not the substring that also appears inside the auto block's prose.
    if (!new RegExp(`^${esc(RULES_HEADER)}\\s*$`, 'm').test(out)) {
      out = out.trimEnd() + '\n\n' + rulesSeed();
    }
  }

  writeFileSync(path, out);
  return status;
}

function rulesSeed() {
  return `${RULES_HEADER}
<!-- These are project-specific rules and developer preferences. This section is OUTSIDE the auto-generated block above, so it is PERSISTED across \`npx promptpilot-ai sync\`. Whenever a new convention, preference, or project requirement is established, add a bullet here so every future AI session inherits it. -->

- _(none yet — rules added here are inherited by every future AI session)_
`;
}

function buildBlock(scanData, target) {
  const { stack = {}, modules = [], patterns = {}, fileData = {} } = scanData || {};
  const fw = stack.framework;
  const type =
    fw?.type === 'fullstack' ? 'full-stack web app'
    : fw?.type === 'api' ? 'backend API'
    : fw?.type === 'spa' ? 'single-page app'
    : fw?.type === 'mobile' ? `mobile app (${fw?.name || stack.language})`
    : fw?.type === 'library' ? 'library / CLI'
    : `${stack.language || ''} project`;

  const topModules =
    modules.slice(0, 12).map((m) => `- \`${m.path || m.name}\` — ${m.name} (${descType(m.type)})`).join('\n') ||
    '- (none detected yet)';
  const entry = (fileData.entryPoints || []).slice(0, 5).map((e) => `\`${e}\``).join(', ');

  const deeper = [];
  if (target === 'claude' || target === 'both') deeper.push('- Per-module detail: `.claude/context/` (Claude Code).');
  if (target === 'cursor' || target === 'both') deeper.push('- Per-module detail: `.cursor/rules/` (Cursor).');
  deeper.push(`- Conventions detail: \`${target === 'cursor' ? '.cursor/rules/patterns.mdc' : '.claude/context/patterns.md'}\`.`);
  deeper.push('- Multi-repo frontend↔backend API map: `.claude/context/bridge.md` (if present).');

  return `${MARKER_START}
# AGENTS.md

> Auto-generated by promptpilot-ai. This block is refreshed from the code on every \`npx promptpilot-ai sync\` — edit OUTSIDE the markers (see "Project rules" below) to keep your changes. Read natively by Claude Code, Codex, Cursor, Copilot, Gemini CLI, Aider, Windsurf, Zed and other agents.

## Project
${fw ? `${fw.name}${fw.version ? ' ' + fw.version : ''}` : stack.language || 'Project'} — ${type} (${stack.language || 'unknown language'}).

## Setup & commands
\`\`\`
${commandsBlock(stack)}
\`\`\`

## Stack
- Language: ${stack.language || 'n/a'} · Runtime: ${stack.runtime || 'n/a'} · Package manager: ${stack.packageManager || 'n/a'}
- Framework: ${fw?.name || 'none'} · Build: ${stack.buildTool || 'default'}
- Database: ${stack.database || 'none'} · ORM: ${stack.orm || 'none'}
- UI: ${stack.uiLibrary || 'none'} · Styling: ${patterns.cssApproach || 'n/a'} · State: ${patterns.stateManagement || stack.stateManagement || 'n/a'}
- Tests: ${stack.testFramework || 'none'}

## Project structure
${topModules}${entry ? `\n\nEntry points: ${entry}` : ''}

${buildMandatoryStandards(scanData)}

## Keeping rules current
- The block above is regenerated from the code by \`npx promptpilot-ai sync\` — do not hand-edit it.
- When the developer establishes a **new convention, preference, or project requirement**, append it as a bullet under the developer-maintained "Project rules" section below (outside this block) so all future sessions inherit it.

## Deeper context
${deeper.join('\n')}
${MARKER_END}`;
}

function descType(type) {
  return (
    {
      feature: 'business logic',
      ui: 'UI components',
      api: 'API routes / controllers',
      database: 'DB models / schema',
      infra: 'shared utilities / infra',
      config: 'configuration',
      routes: 'page routes',
    }[type] || type || 'module'
  );
}

function esc(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
