import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { scanEndpoints } from '../scanner/endpoint-scanner.js';
import { scanApiCalls } from '../scanner/api-call-scanner.js';

function normalizePath(p) {
  // Strip query strings, trailing slashes, normalize to lowercase for matching
  return p.replace(/\?.*$/, '').replace(/\/+$/, '').toLowerCase() || '/';
}

function pathsMatch(backendPath, frontendPath) {
  const bp = normalizePath(backendPath);
  const fp = normalizePath(frontendPath);
  if (bp === fp) return true;
  // Allow /api prefix on frontend: /api/users matches /users
  if (fp.startsWith('/api') && fp.slice(4) === bp) return true;
  return false;
}

export function generateBridgeFile(cwd, frontendRepo, backendRepo) {
  const endpoints = scanEndpoints(backendRepo.path);
  const apiCalls = scanApiCalls(frontendRepo.path);

  const matched = [];
  const unmatchedFrontend = [];
  const unmatchedBackend = [...endpoints];

  for (const call of apiCalls) {
    const match = endpoints.find(
      (ep) => ep.method === call.method && pathsMatch(ep.path, call.path)
    );
    if (match) {
      matched.push({ call, endpoint: match });
      const idx = unmatchedBackend.indexOf(match);
      if (idx !== -1) unmatchedBackend.splice(idx, 1);
    } else {
      unmatchedFrontend.push(call);
    }
  }

  const frontendLabel = frontendRepo.stack?.framework?.name || 'Frontend';
  const backendLabel = backendRepo.stack?.framework?.name || 'Backend';

  let md = `# Frontend ↔ Backend API Bridge

## Repo Layout
- **Frontend**: \`${frontendRepo.name}/\` (${frontendLabel}, ${frontendRepo.stack?.language || 'unknown'})
- **Backend**: \`${backendRepo.name}/\` (${backendLabel}, ${backendRepo.stack?.language || 'unknown'})

## How to Use This File
When asked to implement a UI feature that needs an API:
1. Find the relevant row in the Endpoint Map below
2. Read both the frontend component AND the backend controller file
3. If no matching endpoint exists, implement it in both repos together

---

## Endpoint Map (${matched.length} matched)

`;

  if (matched.length > 0) {
    md += `| Method | Path | Frontend File | Backend File | Handler |\n`;
    md += `|--------|------|--------------|--------------|--------|\n`;
    for (const { call, endpoint } of matched) {
      const handler = endpoint.handler ? `\`${endpoint.handler}()\`` : '—';
      md += `| ${call.method} | \`${endpoint.path}\` | \`${call.file}\` | \`${endpoint.file}\` | ${handler} |\n`;
    }
  } else {
    md += `_No matched endpoints yet. Run \`npx promptpilot-ai sync\` after adding API calls and controllers._\n`;
  }

  if (unmatchedFrontend.length > 0) {
    md += `\n## Unmatched Frontend Calls (no backend endpoint found)\n\n`;
    md += `| Method | Path | Frontend File |\n`;
    md += `|--------|------|---------------|\n`;
    for (const call of unmatchedFrontend) {
      md += `| ${call.method} | \`${call.path}\` | \`${call.file}\` |\n`;
    }
  }

  if (unmatchedBackend.length > 0) {
    md += `\n## Unmatched Backend Endpoints (no frontend consumer found)\n\n`;
    md += `| Method | Path | Backend File | Handler |\n`;
    md += `|--------|------|--------------|--------|\n`;
    for (const ep of unmatchedBackend) {
      const handler = ep.handler ? `\`${ep.handler}()\`` : '—';
      md += `| ${ep.method} | \`${ep.path}\` | \`${ep.file}\` | ${handler} |\n`;
    }
  }

  md += `\n---\n_Generated by promptpilot-ai. Run \`npx promptpilot-ai sync\` to update._\n`;

  const contextDir = join(cwd, '.claude', 'context');
  mkdirSync(contextDir, { recursive: true });
  writeFileSync(join(contextDir, 'bridge.md'), md);

  return { matched: matched.length, unmatchedFrontend: unmatchedFrontend.length, unmatchedBackend: unmatchedBackend.length };
}
