import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { buildMandatoryStandards } from './standards.js';

const MARKER_START = '<!-- promptpilot-ai:start -->';
const MARKER_END = '<!-- promptpilot-ai:end -->';

export function updateClaudeMd(cwd, scanData) {
  const claudeMdPath = join(cwd, 'CLAUDE.md');
  const block = buildBlock(scanData);

  if (!existsSync(claudeMdPath)) {
    writeFileSync(claudeMdPath, block);
    return 'created';
  }

  const existing = readFileSync(claudeMdPath, 'utf8');

  if (existing.includes(MARKER_START)) {
    const updated = existing.replace(
      new RegExp(`${escapeRegex(MARKER_START)}[\\s\\S]*?${escapeRegex(MARKER_END)}`),
      () => block
    );
    writeFileSync(claudeMdPath, updated);
    return 'updated';
  }

  writeFileSync(claudeMdPath, existing.trimEnd() + '\n\n' + block);
  return 'appended';
}

function buildBlock(scanData) {
  const { stack = {}, modules = [] } = scanData || {};
  const moduleNames = modules.map((m) => m.name);

  return `${MARKER_START}
# PromptPilot AI Project Context

> Auto-generated by promptpilot-ai. Do not edit this section manually — run \`npx promptpilot-ai sync\` to update.

## How to Use Context

Before making any changes, read the relevant context files:

- **Project overview** → \`.claude/context/architecture.md\`
- **Tech stack & commands** → \`.claude/context/stack.md\`
- **Code patterns & conventions** → \`.claude/context/patterns.md\`
- **Module details** → \`.claude/context/modules/<module-name>.md\`

## Available Modules

${moduleNames.map((m) => `- \`${m}\` → \`.claude/context/modules/${m.replace(/[^a-z0-9-]/gi, '-').toLowerCase()}.md\``).join('\n')}

## Mandatory standards

${buildMandatoryStandards(scanData, { compact: true })}
- **Read module context** before modifying files in that module; use \`${stack.packageManager || 'the project package manager'}\`.

Full standards: \`.claude/context/patterns.md\`. Project-specific rules & developer preferences live in **AGENTS.md → Project rules** — when a new convention or requirement is established, append it there so it persists across syncs.

## Context Sync

If you add a new module or significantly restructure the project, run:
\`\`\`
npx promptpilot-ai sync
\`\`\`
${MARKER_END}`;
}

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
