import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const MARKER_START = '<!-- claudex:start -->';
const MARKER_END = '<!-- claudex:end -->';

export function updateClaudeMd(cwd, stack, modules) {
  const claudeMdPath = join(cwd, 'CLAUDE.md');
  const block = buildBlock(stack, modules);

  if (!existsSync(claudeMdPath)) {
    writeFileSync(claudeMdPath, block);
    return 'created';
  }

  const existing = readFileSync(claudeMdPath, 'utf8');

  if (existing.includes(MARKER_START)) {
    const updated = existing.replace(
      new RegExp(`${escapeRegex(MARKER_START)}[\\s\\S]*?${escapeRegex(MARKER_END)}`),
      block
    );
    writeFileSync(claudeMdPath, updated);
    return 'updated';
  }

  writeFileSync(claudeMdPath, existing.trimEnd() + '\n\n' + block);
  return 'appended';
}

function buildBlock(stack, modules) {
  const moduleNames = modules.map((m) => m.name);

  return `${MARKER_START}
# Claudex Project Context

> Auto-generated by claudex. Do not edit this section manually — run \`npx claudex sync\` to update.

## How to Use Context

Before making any changes, read the relevant context files:

- **Project overview** → \`.claude/context/architecture.md\`
- **Tech stack & commands** → \`.claude/context/stack.md\`
- **Code patterns & conventions** → \`.claude/context/patterns.md\`
- **Module details** → \`.claude/context/modules/<module-name>.md\`

## Available Modules

${moduleNames.map((m) => `- \`${m}\` → \`.claude/context/modules/${m.replace(/[^a-z0-9-]/gi, '-').toLowerCase()}.md\``).join('\n')}

## Key Rules

- **Never duplicate code** — search for existing implementations before creating new ones
- **Follow detected patterns** — see \`.claude/context/patterns.md\`
- **Use the correct package manager**: \`${stack.packageManager}\`
${stack.language === 'TypeScript' ? '- **TypeScript strict mode** — no `any`, always use specific types\n' : ''}- **Read module context** before modifying files in that module

## Context Sync

If you add a new module or significantly restructure the project, run:
\`\`\`
npx claudex sync
\`\`\`
${MARKER_END}`;
}

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
