import { mkdirSync, writeFileSync, existsSync, readFileSync, readdirSync } from 'fs';
import { join } from 'path';
import {
  buildArchitecture,
  buildStack,
  buildPatterns,
  buildModule,
  moduleFilename,
} from './context.js';
import { buildMandatoryStandards } from './standards.js';

// Generates Gemini CLI context: a root GEMINI.md (the CLAUDE.md analog) that
// @imports per-module context written under .gemini/context/, plus a merge-safe
// .gemini/settings.json, custom .gemini/commands/*.toml (transpiled from the
// shared Markdown command templates), and a .geminiignore.
//
// Refs (google-gemini/gemini-cli main-branch docs):
//   - context file: GEMINI.md, hierarchical, @path imports in the body
//   - settings: .gemini/settings.json (nested v2), context.fileName, mcpServers
//   - commands: .gemini/commands/*.toml — `prompt` (req) + `description`, {{args}}
//   - ignore: .geminiignore (.gitignore-style)

const MARKER_START = '<!-- promptpilot-ai:start -->';
const MARKER_END = '<!-- promptpilot-ai:end -->';

const IGNORE_DIRS = [
  'node_modules', 'dist', 'build', '.next', '.turbo', 'coverage', 'vendor',
  'storage', '__pycache__', '.venv', 'venv', '.git', '.expo', '.dart_tool',
  'Pods', 'DerivedData', '.gradle',
];

// ── context (GEMINI.md + .gemini/context/*.md) ───────────────────────
export function generateGemini(cwd, { fileData, stack, modules, patterns }) {
  if (patterns?.stateManagement) stack = { ...stack, stateManagement: patterns.stateManagement };

  const contextDir = join(cwd, '.gemini', 'context');
  const modulesDir = join(contextDir, 'modules');
  mkdirSync(modulesDir, { recursive: true });

  writeFileSync(join(contextDir, 'architecture.md'), buildArchitecture(fileData, stack, modules));
  writeFileSync(join(contextDir, 'stack.md'), buildStack(stack, patterns));
  writeFileSync(
    join(contextDir, 'patterns.md'),
    buildPatterns(patterns, stack) + '\n\n' + buildMandatoryStandards({ stack, patterns, modules })
  );

  const written = [];
  for (const mod of modules) {
    const filename = moduleFilename(mod.name);
    writeFileSync(join(modulesDir, filename), buildModule(mod));
    written.push({ name: mod.name, filename, fileCount: mod.files.length });
  }

  writeGeminiMd(cwd, { stack, modules });
  writeGeminiIgnore(cwd);
  return written;
}

export function regenerateGeminiModuleFiles(cwd, modules) {
  const modulesDir = join(cwd, '.gemini', 'context', 'modules');
  mkdirSync(modulesDir, { recursive: true });
  for (const mod of modules) {
    writeFileSync(join(modulesDir, moduleFilename(mod.name)), buildModule(mod));
  }
}

function writeGeminiMd(cwd, { stack, modules }) {
  const path = join(cwd, 'GEMINI.md');
  const block = buildGeminiBlock({ stack, modules });

  if (!existsSync(path)) {
    writeFileSync(path, block);
    return 'created';
  }
  const existing = readFileSync(path, 'utf8');
  if (existing.includes(MARKER_START)) {
    const updated = existing.replace(
      new RegExp(`${esc(MARKER_START)}[\\s\\S]*?${esc(MARKER_END)}`),
      () => block
    );
    writeFileSync(path, updated);
    return 'updated';
  }
  writeFileSync(path, existing.trimEnd() + '\n\n' + block);
  return 'appended';
}

function buildGeminiBlock({ stack, modules }) {
  const moduleLines =
    modules.map((m) => `- \`${m.name}\` → \`.gemini/context/modules/${moduleFilename(m.name)}\``).join('\n') ||
    '- (none detected yet)';

  // @import the three core files so Gemini always has architecture/stack/patterns
  // in context. Per-module files are listed (read on demand) to avoid bloating
  // every prompt with the full module breakdown.
  return `${MARKER_START}
# PromptPilot AI Project Context

> Auto-generated by promptpilot-ai for Gemini CLI. Do not edit this section — run \`npx promptpilot-ai sync\` to update. Edit project rules in AGENTS.md instead.

## Imported context

@./.gemini/context/architecture.md
@./.gemini/context/stack.md
@./.gemini/context/patterns.md

## Module context (read on demand)

${moduleLines}

## Mandatory standards

${buildMandatoryStandards({ stack, modules }, { compact: true })}
- **Read the relevant module file** before modifying files in that module; use \`${stack.packageManager || 'the project package manager'}\`.

Project-specific rules & developer preferences live in **AGENTS.md → Project rules** — append new conventions there so they persist across syncs.

## Context sync

If you add a new module or restructure the project, run:
\`\`\`
npx promptpilot-ai sync
\`\`\`
${MARKER_END}`;
}

// ── .geminiignore ─────────────────────────────────────────────────────
function writeGeminiIgnore(cwd) {
  const path = join(cwd, '.geminiignore');
  if (existsSync(path)) return; // never clobber a user's ignore file
  const body = [
    '# Auto-generated by promptpilot-ai — directories Gemini CLI should skip.',
    ...IGNORE_DIRS.map((d) => `${d}/`),
  ].join('\n') + '\n';
  writeFileSync(path, body);
}

// ── .gemini/settings.json ─────────────────────────────────────────────
// Nested v2 shape. Adds AGENTS.md to context.fileName so the universal
// AGENTS.md is read too, and scaffolds an empty mcpServers block.
export function writeGeminiSettings(cwd) {
  const dir = join(cwd, '.gemini');
  const path = join(dir, 'settings.json');
  mkdirSync(dir, { recursive: true });

  const desired = {
    context: { fileName: ['AGENTS.md', 'GEMINI.md'] },
    mcpServers: {},
  };

  if (existsSync(path)) {
    try {
      const existing = JSON.parse(readFileSync(path, 'utf8'));
      let changed = false;

      existing.context = existing.context || {};
      const names = new Set(
        Array.isArray(existing.context.fileName)
          ? existing.context.fileName
          : existing.context.fileName
            ? [existing.context.fileName]
            : []
      );
      for (const n of desired.context.fileName) {
        if (!names.has(n)) { names.add(n); changed = true; }
      }
      existing.context.fileName = [...names];

      if (!existing.mcpServers) { existing.mcpServers = {}; changed = true; }

      if (changed) writeFileSync(path, JSON.stringify(existing, null, 2));
      return 'merged';
    } catch {}
  }

  writeFileSync(path, JSON.stringify(desired, null, 2));
  return 'created';
}

// ── .gemini/commands/*.toml (transpiled from templates/commands/*.md) ─
// Gemini commands are TOML with a `prompt` (required) + `description`, and use
// {{args}} (NOT Claude's $ARGUMENTS). The Markdown body is carried verbatim in a
// TOML literal string, with .claude/ paths rewritten to .gemini/.
export function generateGeminiCommands(cwd, templateCommandsDir, { force = false } = {}) {
  const dir = join(cwd, '.gemini', 'commands');
  mkdirSync(dir, { recursive: true });

  const written = [];
  for (const file of readdirSync(templateCommandsDir)) {
    if (!file.endsWith('.md')) continue;
    const name = file.replace(/\.md$/, '');
    const dest = join(dir, `${name}.toml`);
    if (!force && existsSync(dest)) continue;

    const md = readFileSync(join(templateCommandsDir, file), 'utf8');
    writeFileSync(dest, mdToToml(name, md));
    written.push(name);
  }
  return written;
}

function mdToToml(name, md) {
  const body = stripFrontmatter(md)
    .replace(/\$ARGUMENTS/g, '{{args}}')        // Gemini arg placeholder
    .replace(/!`([^`]+)`/g, '!{$1}')            // Claude exec → Gemini exec shorthand
    .replace(/\.claude\/context\//g, '.gemini/context/')
    .replace(/\.claude\/skills\//g, '.gemini/skills/')
    .trim();

  const description = describeCommand(name);

  // TOML literal multi-line string ('''...''') preserves the body verbatim — no
  // escape processing of backslashes/quotes/backticks. {{args}} stays literal and
  // is substituted by Gemini at call time. Bodies never contain a ''' sequence.
  return `description = ${tomlString(description)}\nprompt = '''\n${body}\n'''\n`;
}

function describeCommand(name) {
  return {
    ask: 'Natural language → plan → execute, cross-repo aware',
    plan: 'Interactive planning only — shows the approach, writes no code',
    sync: 'Re-scan and regenerate all project context',
    'pp-stats': 'Show the context stats dashboard',
    'pp-help': 'List all commands and their use-cases',
  }[name] || `promptpilot-ai ${name} command`;
}

function tomlString(s) {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

// Drop a leading YAML frontmatter block (Claude command templates like pp-help/
// pp-stats start with one) so it doesn't leak into the transpiled prompt body.
function stripFrontmatter(md) {
  return md.replace(/^---\n[\s\S]*?\n---\n/, '');
}

// ── helpers ───────────────────────────────────────────────────────────
export function geminiInstalled(cwd) {
  return existsSync(join(cwd, 'GEMINI.md')) || existsSync(join(cwd, '.gemini'));
}

function esc(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
